version: "4.9"
services:
  db:
    image: "mysql"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=todo
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "db"
