version: "3.1"
services:
  db:
    image: "mysql"
    container_name: "db"
    ports:
      - "3306:3306"
    environment:
      
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /usr/src/mysql-data:/var/lib/mysql
    
  api:
    
    build: .
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=YES
    ports:
      - "3000:3000"
    restart: always  
    depends_on:
      - "db"
